/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : CPU
 #	author : miyako
 #	2017/06/19
 #
 # --------------------------------------------------------------------------------*/



// --- CPU
void CPU_Get_count(sLONG_PTR *pResult, PackagePtr pParams);
